# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rock-queue}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Grzegorz Kazulak", "Wojtek Mach", "Piotr Chmolowski", "Daniel Chrusciak"]
  s.autorequire = %q{rock-queue}
  s.date = %q{2010-09-01}
  s.description = %q{A unified interface for various messaging queues}
  s.email = %q{gregorz.kazulak@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
     "Rakefile",
     "lib/rock-queue.rb",
     "lib/rock-queue/active_record_helper.rb",
     "lib/rock-queue/adapters/beanstalkd.rb",
     "lib/rock-queue/adapters/delayed_job.rb",
     "lib/rock-queue/adapters/resque.rb",
     "lib/rock-queue/config.rb",
     "lib/rock-queue/errors.rb",
     "lib/rock-queue/notifiers.rb",
     "lib/rock-queue/notifiers/abstract_notifier.rb",
     "lib/rock-queue/notifiers/email_notifier.rb",
     "lib/rock-queue/queue_object.rb",
     "lib/rock-queue/tasks.rb",
     "lib/rock-queue/web.rb",
     "lib/rock-queue/web/views/dashboard.erb",
     "lib/rock-queue/worker.rb"
  ]
  s.homepage = %q{http://github.com/grzegorzkazulak/rock-queue}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A unified interface for various messaging queues}
  s.test_files = [
    "spec/active_record_helper_spec.rb",
     "spec/beanstalkd_spec.rb",
     "spec/email_notifier_spec.rb",
     "spec/fixtures.rb",
     "spec/notifiers_spec.rb",
     "spec/queue_object_spec.rb",
     "spec/resque_queue_spec.rb",
     "spec/rock_queue_spec.rb",
     "spec/shared.rb",
     "spec/spec_helper.rb",
     "spec/worker_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<resque>, [">= 1.9.9"])
      s.add_runtime_dependency(%q<mail>, [">= 2.2.5"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<resque>, [">= 1.9.9"])
      s.add_dependency(%q<mail>, [">= 2.2.5"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<resque>, [">= 1.9.9"])
    s.add_dependency(%q<mail>, [">= 2.2.5"])
  end
end

